apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-backend-ingress
  namespace: backend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: application-backend
            port:
              number: 80