apiVersion: v1
kind: Pod
metadata:
  name: debug-backend
  namespace: backend
spec:
  containers:
    - name: debug
      image: eugeneowner/application-backend:test
      command: ["sleep"]
      args: ["3600"]
  restartPolicy: Never